apiVersion: 1
prune: true

datasources:
  - name: Loki
    uid: loki
    orgId: 1
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    editable: false
    jsonData:
      maxLines: 1000
