apiVersion: 1

contactPoints:
  - orgId: 1
    name: epiber-operators
    receivers:
      - uid: epiber-operator-email
        type: email
        disableResolveMessage: false
        settings:
          addresses: $EPIBER_ALERT_EMAIL
          singleEmail: true

policies:
  - orgId: 1
    receiver: epiber-operators
    group_by: [grafana_folder, alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
